[package]
name = "examples"
version = "0.0.1"
edition = "2021"
publish = false
default-run = "re-export-test"

[[bin]]
name = "silentpaymentscanner"
path = "src/silentpaymentscanner.rs"

[[bin]]
name = "re-export-test"
path = "src/re-export-test.rs"

[[bin]]
name = "bitcoinkernal-tests"
path = "src/bitcoinkernal-tests.rs"

[dependencies]
silentpayments = "0.1"
bitcoin = "0.31"
secp256k1 = "0.28"
env_logger = "0.11"
log = "0.4"
bitcoinkernel = { path = ".." }
